[build]
    command = "npm run build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "10.15"
    YARN_VERSION = "1.21.1"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

# Favicon
[[redirects]]
    from = "/assets/images/touch/*"
    to = "/assets/images/favicon/:splat"
    status = 301

# 404s
[[redirects]]
    from = "*"
    to = "/404"
    status = 404
